### PR TITLE
added mps functionality

### PR DESCRIPTION
**Pull request by benjamin-bertram**

### CODE REVIEW

**Comment by madjuju** [comment]
Please Merge. It is ok

**Comment by ptits** [comment]
Using the same seed gives slightly different images

**Comment by blue-pen5805** [comment]
I cannot merge because it probably causes an error in version 1.7.0 of A1111.

**Comment by benjamin-bertram** [comment]
I currently use it in forge, true, but what is the root cause of the error? I might can solve try to find a way at the weekend

**Comment by HogansJoe** [comment]
Mac User here: AssertionError: Torch not compiled with CUDA enabled. Where could i change device to mps?

**Comment by benjamin-bertram** [comment]
> Mac User here: AssertionError: Torch not compiled with CUDA enabled. Where could i change device to mps?

If you install https://github.com/benjamin-bertram/sdweb-easy-stablecascade-diffusers it should solve this issue (thats why i wrote it).

A quick fix would be to search and replace "cuda" with "mps" and change the dytpe to float32 instead of bfloat16 in line 41: https://github.com/blue-pen5805/sdweb-easy-stablecascade-diffusers/blob/71d37440bdfa776ce19341257eb372fd58bf1c97/scripts/easy_stablecascade_diffusers.py#L41

**Comment by blue-pen5805** [comment]
> I currently use it in forge, true, but what is the root cause of the error? I might can solve try to find a way at the weekend

`modules.infotext_utils` does not exist in 1.7.0. you are welcome to make changes, but this issue will be resolved when 1.8.0 is released.
If 1.8.0 is released, I plan to merge this PR.

**Comment by HogansJoe** [comment]
> > Mac User here: AssertionError: Torch not compiled with CUDA enabled. Where could i change device to mps?
> 
> If you install https://github.com/benjamin-bertram/sdweb-easy-stablecascade-diffusers it should solve this issue (thats why i wrote it).
> 
> A quick fix would be to search and replace "cuda" with "mps" and change the dytpe to float32 instead of bfloat16 in line 41:
> 
> https://github.com/blue-pen5805/sdweb-easy-stablecascade-diffusers/blob/71d37440bdfa776ce19341257eb372fd58bf1c97/scripts/easy_stablecascade_diffusers.py#L41


Works! Tested in Automatic1111 and Forge. Running on a MacBook Pro M2.

**Comment by zexcster** [comment]
Does it work with python: 3.10.11 ?

Because both a1111 or Forge version give me this error (typing_extensions has the latest version installed = 4.9 )

 RuntimeError: Failed to import diffusers.pipelines.stable_cascade.pipeline_stable_cascade because of the following error (look up to see its traceback):
    cannot import name 'List' from 'typing_extensions'
